import { Text } from "./Text";
import { Heading } from "./Heading";
import { Button } from "./Button";
import PartnerSlider from "./PartnerSlider";
import { ServiceItem } from "./ServiceItem";
import { ServicesComponent } from "./Services";
import { Img } from "./Img";
import Popup from "./Popup";
import Notification from "./Notification";
import ContactForm from "./ContactForm";
export { ContactForm, Notification, Popup, PartnerSlider, ServiceItem, Text, Heading, Button, Img, ServicesComponent };
