import { Text } from "./Text";
import { Heading } from "./Heading";
import { Button } from "./Button";
import PartnerSlider from "./PartnerSlider";
import { ServiceItem } from "./ServiceItem";
import { ServicesComponent } from "./Services";
import { Img } from "./Img";
import Popup from "./Popup";
import PopupManager from "./PopupManager";
import Cookies from "./Cookies";
import Notification from "./Notification";
import ContactForm from "./ContactForm";
import Changelogs from "./Changelogs";
import Contact from "./Contact";
import Contactbar from "./Contactbar";
import PCInfoComponent from "./PCInfoComponent";
export {Contact,Contactbar, Changelogs, PopupManager, PCInfoComponent, Cookies, ContactForm, Notification, Popup, PartnerSlider, ServiceItem, Text, Heading, Button, Img, ServicesComponent };
